apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: test-app-deployment
  namespace: default
spec:
  scaleTargetRef:
    kind: Deployment
    name: test-app-deployment
    apiVersion: apps/v1
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
